### ISSUE TITLE
Broken

### ISSUE THREAD

**Issue by el3ment** [chrisranderson/finch#1]
Installed. Doesn't work.

  0%|          | 0/10000 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mnt/pccfs/backed_up/robert/678/feedback_alignment.py", line 85, in <module>
    nn_viz.visualize_parameters(sess)
  File "/mnt/pccfs/backed_up/robert/678/finch/nn_viz.py", line 72, in visualize_parameters
    shapes = [x.get_shape() for x in variables]
TypeError: 'NoneType' object is not iterable

**Comment by chrisranderson** [comment]
Fixed by 601024b0ffed61eea84effce5eba72e1cce70b10.
